# Object-Oriented Programming

In [2]:
class HumanBeing(object):
    def __init__(self, first_name, eye_color):
        self.first_name = first_name
        self.eye_color= eye_color
        self.position = 0
    def walk_steps(self, steps):
        self.position += steps

In [3]:
Sandra = HumanBeing('Sandra', 'blue')

In [4]:
Sandra.first_name

'Sandra'

In [5]:
Sandra.position

0

In [6]:
Sandra.walk_steps(5)

In [7]:
Sandra.position

5

## Python Objects

### int

In [8]:
n = 5

In [9]:
type(n)

int

In [10]:
n.numerator

5

In [11]:
n.bit_length()

3

In [12]:
n + n

10

In [13]:
2 * n

10

In [14]:
n.__sizeof__()

28

### list

In [15]:
l = [1, 2, 3, 4]

In [16]:
type(l)

list

In [17]:
l[0]

1

In [18]:
l.append(10)

In [19]:
l + l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [20]:
2 * l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [21]:
l.__sizeof__()

104

### ndarray

In [22]:
import numpy as np

In [23]:
a = np.arange(16).reshape((4, 4))

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
type(a)

numpy.ndarray

In [26]:
a.nbytes

64

In [27]:
a.sum()

120

In [28]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [29]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [30]:
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [31]:
sum(a)

array([24, 28, 32, 36])

In [32]:
np.sum(a)

120

In [33]:
a.__sizeof__()

120

### DataFrame

In [34]:
import pandas as pd

In [35]:
df = pd.DataFrame(a, columns=list('abcd'))

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [39]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [40]:
df+ df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [41]:
2 * df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [42]:
np.sum(df)

a    24
b    28
c    32
d    36
dtype: int64

In [43]:
df.__sizeof__()

192

## Python Classes

In [44]:
class FinancialInstrument():
    pass

In [45]:
fi = FinancialInstrument()

In [46]:
type(fi)

__main__.FinancialInstrument

In [47]:
fi

In [48]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x00000273883A3850>'

In [49]:
fi.price = 100

In [50]:
fi.price

100

In [51]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price

In [52]:
FinancialInstrument.author

'Yves Hilpisch'

In [58]:
aapl = FinancialInstrument('AAPL', 100)

In [59]:
aapl.symbol

'AAPL'

In [60]:
aapl.price

100

In [61]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price

In [62]:
fi = FinancialInstrument('AAPL', 100)

In [63]:
fi.get_price()

100

In [64]:
fi.set_price(105)

In [65]:
fi.get_price()

105

In [66]:
fi.price

105

In [67]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [68]:
fi = FinancialInstrument('AAPL', 100)

In [69]:
fi.get_price()

100

In [70]:
fi.__price

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [72]:
fi._FinancialInstrument__price

100

In [73]:
fi._FinancialInstrument__price = 105

In [74]:
fi.set_price(100)

In [77]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
            self.position.get_price()

In [78]:
pp = PortfolioPosition(fi, 10)

In [79]:
pp.get_position_size()

10

In [80]:
pp.get_position_value()

1000

In [81]:
pp.position.get_price()

100

In [82]:
pp.position.set_price(105)

In [83]:
pp.get_position_value()

1050

## Python Data Model

In [2]:
class Vector(object):
    def __init__(self,x=0, y=0, z=0):
        self.x=x
        self.y=y
        self.z=z
    

In [3]:
v = Vector(1, 2, 3)

In [4]:
v

In [6]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r,)' % (self.x, self.y, self.z)

In [7]:
v = Vector(1, 2, 3)

In [8]:
v

Vector(1, 2, 3,)

In [9]:
print(v)

Vector(1, 2, 3,)


In [10]:
class Vector(Vector):
    def __abs__(self):
        return(self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))

In [11]:
v = Vector(1, 2, -1)

In [12]:
abs(v)

2.449489742783178

In [13]:
bool(v)

True

In [14]:
v = Vector()

In [15]:
v

Vector(0, 0, 0,)

In [16]:
abs(v)

0.0

In [17]:
bool(v)

False

In [18]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
        

In [19]:
v = Vector(1, 2, 3)

In [20]:
v + Vector(2, 3, 4)

Vector(3, 5, 7,)

In [21]:
v * 2

Vector(2, 4, 6,)

In [22]:
class Vector(Vector):
    def __len__(self):
        return 3
    def __getitem__(self, i):
        if i in[0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [23]:
v = Vector(1, 2, 3)

In [24]:
len(v)

3

In [25]:
v[0]

1

In [26]:
v[-2]

2

In [27]:
v[3]

IndexError: Index out of range.

In [28]:
class Vecvotr(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [30]:
v = Vector(1, 2, 3)

In [31]:
for i in range(3):
    print(v[i])

1
2
3


In [32]:
for coordinate in v:
    print(coordinate)
    

1
2
3
