# Python for Finance

## Numerical Computing with Numpy

### Arrays with Python Lists

In [2]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [3]:
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [4]:
m[1][0]

0.5

In [5]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [7]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [8]:
c[1][1][0]

1

In [11]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v,v,v]
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [14]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.5]
m = 3 * [deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.5],
 [0.5, 0.75, 1.0, 1.5, 2.5],
 [0.5, 0.75, 1.0, 1.5, 2.5]]

In [15]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.5],
 [0.5, 0.75, 1.0, 1.5, 2.5],
 [0.5, 0.75, 1.0, 1.5, 2.5]]

### The Python Array Class

In [16]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [17]:
import array

In [12]:
a = array.array('f', v)
a

NameError: name 'array' is not defined

In [19]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [20]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [21]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [22]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [23]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [24]:
with open('array.apy', 'wb') as f:
    a.tofile(f)

In [25]:
b = array.array('f')

In [29]:
with open('array.apy', 'rb') as f:
    b.fromfile(f,5)

In [30]:
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [31]:
b = array.array('d')

In [4]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 2)

NameError: name 'array' is not defined

### Regular Numpy Arrays

In [2]:
import numpy as np

In [16]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
type(a)

numpy.ndarray

In [14]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [15]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
a = np.arange(8, dtype=np.float)
a

<ipython-input-21-4ba113f08619>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.arange(8, dtype=np.float)


array([0., 1., 2., 3., 4., 5., 6., 7.])

In [22]:
a[5:]

array([5., 6., 7.])

In [23]:
a[:2]

array([0., 1.])

In [24]:
a.sum()

28.0

In [25]:
a.std()

2.29128784747792

In [26]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [27]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [28]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [29]:
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [30]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [31]:
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [32]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [33]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [34]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [35]:
np.sqrt(2.5)

1.5811388300841898

In [13]:
import math

In [37]:
math.sqrt(2.5)

1.5811388300841898

In [38]:
mth.sqrt(a)

NameError: name 'mth' is not defined

In [39]:
%timeit np.sqrt(2.5)

498 ns ± 10.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [40]:
%timeit math.sqrt(2.5)

95.5 ns ± 1.98 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


#### Multiple Dimensions

In [41]:
b = np.array([a, a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [42]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [43]:
b[0, 2]

2.0

In [44]:
b[:, 1]

array([1., 2.])

In [45]:
b.sum()

84.0

In [46]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [47]:
b.sum(axis=1)

array([28., 56.])

In [48]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [49]:
c = np.ones((2, 3, 4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [52]:
d = np.zeros_like(c, dtype='f16', order='C')
d

TypeError: data type 'f16' not understood

In [53]:
d = np.ones_like(c, dtype='f16', order='C')
d

TypeError: data type 'f16' not understood

In [54]:
e = np.empty((2, 3, 2))
e

array([[[9.36753010e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 3.27675490e+179]],

       [[3.50669715e-033, 1.03980259e-042],
        [6.45081992e-067, 1.21045732e+161],
        [5.64581228e-038, 3.79837659e+175]]])

In [55]:
f = np.empty_like(c)
f

array([[[1928623000,        441,         64,          0],
        [         0,          0,          0,          0],
        [         0,          0,  959996467, 1697920817]],

       [[ 892953654,  959591731,  811754036,  926363705],
        [ 959525477,  842097713, 1664497717, 1633761332],
        [ 909523248,  942880306, 1650734134, 1684222566]]], dtype=int32)

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
g = np.linspace(5, 10, 12)
g

array([ 5.        ,  5.45454545,  5.90909091,  6.36363636,  6.81818182,
        7.27272727,  7.72727273,  8.18181818,  8.63636364,  9.09090909,
        9.54545455, 10.        ])

#### Metainformation

In [5]:
g.size

12

In [6]:
g.itemsize

8

In [7]:
g.ndim

1

In [11]:
g.shape

(12,)

In [12]:
g.dtype

dtype('float64')

In [13]:
g.nbytes

96

#### Reshaping and Resizing

In [14]:
g = np.arange(15)

In [15]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
g.shape

(15,)

In [17]:
g.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [20]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [21]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.resize(g, (3, 1))

array([[0],
       [1],
       [2]])

In [23]:
np.resize(g, (1, 5))

array([[0, 1, 2, 3, 4]])

In [24]:
np.resize(g, (5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [25]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [27]:
np.vstack((h, 0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [28]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [33]:
for i in h.flat:
    print(i, end=',')    

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [35]:
for i in h.ravel(order='C'):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [36]:
for i in h.ravel(order='F'):
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

#### Boolean Arrays

In [37]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [38]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [40]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [41]:
(h==5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
(h > 4) & (h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [43]:
h[h > 8]

array([ 9, 10, 11, 12, 13, 14])

In [44]:
h[(h > 4) & (h<= 12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
h[(h < 4) | (h >= 12)]

array([ 0,  1,  2,  3, 12, 13, 14])

In [46]:
np.where(h > 7, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
np.where(h % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [48]:
np.where(h <= 7, h * 2, h / 2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

#### Speed Comparison

In [12]:
import random
I = 5000

In [52]:
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]

Wall time: 14.5 s


In [53]:
mat[0][:5]

[0.9074770422102212,
 -0.54745507229188,
 -0.17035684859812217,
 -0.7972900503839825,
 0.3128734592994819]

In [17]:
%time sum([sum(l) for l in mat])

NameError: name 'mat' is not defined

In [55]:
import sys
sum([sys.getsizeof(l) for l in mat])

215160000

In [56]:
%time mat = np.random.standard_normal((I, I))

Wall time: 889 ms


In [57]:
%time mat.sum()

Wall time: 30.9 ms


-2662.143633170587

In [58]:
mat.nbytes

200000000

In [59]:
sys.getsizeof(mat)

200000120

#### Structured Numpy Arrays

In [62]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [63]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [65]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],
              'formats':'0 int float int,int'.split()})

TypeError: data type '' not understood

In [68]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
            ('Jones', 53, 1.72, (2, 2))], dtype=dt)

In [69]:
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [70]:
type(s)

numpy.ndarray

In [71]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [72]:
s['Height'].mean()

1.7750001

In [73]:
s[0]

(b'Smith', 45, 1.83, [0, 1])

In [74]:
s[1]['Age']

53

#### Vectorization

In [75]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [76]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [77]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [78]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [79]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [80]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [81]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [82]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
r.shape

(4, 3)

In [84]:
s = np.arange(0, 12, 4)
s

array([0, 4, 8])

In [85]:
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [86]:
s = np.arange(0, 12, 3)
s

array([0, 3, 6, 9])

In [87]:
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [88]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [89]:
sr = s.reshape(-1, 1)
sr

array([[0],
       [3],
       [6],
       [9]])

In [90]:
sr.shape

(4, 1)

In [91]:
r + s.reshape(-1, 1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [92]:
def f(x):
    return 3 * x + 5

In [93]:
f(0.5)

6.5

In [94]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

#### Memory Layout

In [3]:
x = np.random.standard_normal((1000000, 5))

In [4]:
y = 2 * x + 3

In [6]:
C = np.array((x, y), order='C')

In [7]:
F = np.array((x, y), order='F')

In [8]:
x = 0.0; y = 0.0

In [10]:
C[:2].round(2)

array([[[ 0.49,  0.16, -0.39,  0.4 , -1.98],
        [ 0.25, -0.64, -0.71,  0.19,  0.1 ],
        [ 2.52, -0.08,  0.66,  0.37, -0.89],
        ...,
        [-1.53, -0.05,  0.78, -0.36,  1.63],
        [ 0.15,  0.81,  0.95, -0.78,  0.24],
        [-0.85,  1.46, -1.06, -1.2 , -0.08]],

       [[ 3.98,  3.31,  2.22,  3.81, -0.96],
        [ 3.51,  1.71,  1.58,  3.39,  3.2 ],
        [ 8.03,  2.84,  4.32,  3.73,  1.22],
        ...,
        [-0.07,  2.89,  4.56,  2.29,  6.27],
        [ 3.29,  4.62,  4.9 ,  1.44,  3.47],
        [ 1.3 ,  5.93,  0.87,  0.6 ,  2.84]]])

In [18]:
%timeit C.sum()

12.1 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%timeit F.sum()

12.1 ms ± 303 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%timeit C.sum(axis=0)

18.1 ms ± 383 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%timeit C.sum(axis=1)

30.7 ms ± 796 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
%timeit F.sum(axis=0)

52.9 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
%timeit F.sum(axis=1)

64.6 ms ± 468 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
F = 0.0; C = 0.0